export const SITE_EMOJI = '⚡'
export const SITE_NAME = 'Optionism'
export const SITE_INFO = 'SuperHack2024 Project by Drone'
export const SITE_DESCRIPTION = 'A decentralized derivatives option market built during SuperHack2024'
export const SITE_URL = 'https://no-site.com'
export const SOCIAL_GITHUB = 'SolidityDrone/Optionism'
